    - name: Download Zabbix Agent MSI
      win_get_url:
        url: https://repo.zabbix.com/zabbix/5.4/windows/x86_64/zabbix_agent-5.4.0-windows-amd64-openssl.msi
        dest: C:\Temp\zabbix_agent.msi

    - name: Install Zabbix Agent
      win_package:
        path: C:\Temp\zabbix_agent.msi
        arguments: '/q Server=192.168.9.200'
        state: present