#Playbook to setup Folder Structures for new Fileserver

- hosts: file_servers
  #gather_facts: no
  

  tasks:
  - name: Set a hostname
    ansible.windows.win_hostname:
      name: Woningbouw-FS01

  - name: Install File-Services
    ansible.windows.win_feature:
      name: File-Services
      state: present
      IncludeManagementTools: yes
      register: file-services

#  - name: Create Directory
#    ansible.windows.win_file:
#      path: C:/Project/PRO03
#      state: directory
#      recurse: yes
  
#  - name: Create Directory
#    ansible.windows.win_file:
#      path: C:/Project/PRO03/Afdelingen
#      state: directory
#      recurse: yes

  - name: Create Directory
    ansible.windows.win_file:
      path: C:/Project/PRO03/Afdelingen/Administratie
      state: directory
      recurse: yes      

    

  #- name: Reboot if installing File-Services requires it
   # ansible.windows.win_reboot:
    #when: file-services.reboot_required