
# installs active directory on the server
  - name: Install Active Directory Domain Services
    ansible.windows.win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: adds
# # Pause for promoting DC
#   - name: Pause for 5 minutes
#     ansible.builtin.pause:
#       minutes: 5
# Makes the 2nd Domain Controller
  - name: Promote DC as Domain Controller
    ansible.windows.win_domain_controller:
      dns_domain_name: woningbouw.local
      domain_admin_user: woningbouw\administrator
      domain_admin_password: "{{winadminpass}}"
      safe_mode_password: "{{domain_safe_password}}"
      state: domain_controller
    register: dc_promotion
# Reboot 
  - name: Reboot
    ansible.windows.win_reboot:
      msg: "Promoting DC. Rebooting..."
      pre_reboot_delay: 15
    when: dc_promotion.reboot_required
