  - name: Read the latest version of a kv2 secret from Vault
    community.hashi_vault.vault_read:
      url: https://vault.nasdenissen.synology.me
      path: kv-woningbouw/data/domain-creds
      auth_method: token
      token:
    register: secret
    delegate_to: "127.0.0.1"

# installs active directory on the server
  - name: Install Active Directory Domain Services
    ansible.windows.win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: adds
# # Pause for promoting DC
#   - name: Pause for 5 minutes
#     ansible.builtin.pause:
#       minutes: 5
# Makes the 2nd Domain Controller
  - name: Promote DC as Domain Controller
    ansible.windows.win_domain_controller:
      dns_domain_name: woningbouw.local
      domain_admin_user: woningbouw\administrator
      domain_admin_password: "{{ secret.data.data.data.local_admin }}"
      safe_mode_password: "{{ secret.data.data.data.dc_safe_mode_password }}"
      state: domain_controller
    register: dc_promotion
# Reboot 
  - name: Reboot
    ansible.windows.win_reboot:
      msg: "Promoting DC. Rebooting..."
      pre_reboot_delay: 15
    when: dc_promotion.reboot_required
