- name: Read the latest version of a kv2 secret from Vault
  community.hashi_vault.vault_read:
    url: https://vault.nasdenissen.synology.me
    path: kv-woningbouw/data/domain-creds
    auth_method: token
    token:
  register: secret
  delegate_to: "127.0.0.1"

- name: Create woningbouw OU
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "{{ item }}"
    path: "DC=woningbouw,DC=local"
  loop:
    - WoningUsers
    - WoningComputers
    - WoningServers
    - WoningGroups


- name: Add windows groups
  win_domain_group:
    name: "{{ item }}"
    scope: global
    path: "OU=WoningGroups,DC=woningbouw,DC=local"
  loop:
    - Super_Admins
    - Locatie_Users
      

# create Domain controller admin
- name: Add Windows domain admin
  win_domain_user:
    name: "admin.woningbouw"
    upn: "admin.woningbouw@woningbouw.local"
    state: present
    enabled: yes
    account_locked: no
    groups:
        - Domain Admins
        - Super_Admins
    password: "{{ secret.data.data.data.dc_win_adminpass }}"
    update_password: on_create
    password_expired: false
    firstname: woningbouw
    surname: user
    company: Pinewood
    email: "admin.woningbouw@woningbouw.local"