- name: get deb package
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - php-gd
      - php-xml
      - mysql-server
      - python3
      - python3-pip
    state: present

- name: Install pymysql python package
  ansible.builtin.pip:
    name:
      - pymysql
      - zabbix-api

- name: Install required packages
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present

- name: Create database user with name 'bob' and password '12345' with all database privileges
  community.mysql.mysql_user:
    name: zabbix
    password: zabbix
    priv: "*.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Try to create database as root/nopassword first. If not allowed, pass the credentials
  community.mysql.mysql_db:
    check_implicit_admin: true
    login_user: zabbix
    login_password: zabbix
    name: zabbix
    state: present

# Configure Zabbix server
- name: Configure Zabbix server
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^DBName=", line: "DBName=zabbix" }
    - { regexp: "^DBUser=", line: "DBUser=zabbix" }
    - { regexp: "^DBPassword=", line: "DBPassword=zabbix" }

#
- name: Import Zabbix database schema
  mysql_db:
    name: zabbix
    state: import
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
    login_user: zabbix
    login_password: zabbix

- name: Set Zabbix timezone
  lineinfile:
    path: /etc/zabbix/apache.conf
    regexp: "^php_value date.timezone"
    line: "php_value date.timezone Europe/London"

- name: Restart Zabbix server and frontend
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - zabbix-server
    - apache2
    - zabbix-agent

- name: Set connection specific variables
  set_fact:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
   
# If you want to use Username and Password to be authenticated by Zabbix Server
- name: Set credentials to access Zabbix Server API
  set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix


- name: Create Zabbix User
  zabbix_user:
    #server_url: http://localhost/zabbix # Replace with your Zabbix server URL
    #api_url: http://localhost/api_jsonrpc.php
    #login_user: Admin
    #login_password: zabbix
    usrgrps:
      - Guests
    username: pieter
    passwd: Pieter1234!
    type: Zabbix super admin
    state: present
  register: zabbix_user_result

- name: Display Result
  debug:
    var: zabbix_user_result