 # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install dependencies
    - name: Install dependencies
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-gd
          - libapache2-mod-php
          - php-bcmath
          - php-xml
          - php-mbstring
          #- mariadb-server
          #- mariadb-client
          - python3
          - python3-pip
        state: present
      
    - name: Install pymysql python package
      ansible.builtin.pip:
        name: pymysql
    # Install Zabbix repository key
    - name: Install Zabbix repository key
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    # Add Zabbix repository
    - name: Add Zabbix repository
      apt_repository:
        repo: deb https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu focal main
        state: present

    - name: Update apt cache with zabbix items
      apt:
        update_cache: yes

    # Install Zabbix server, frontend, and agent
    - name: Install Zabbix server, frontend, and agent
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-agent
        state: present

    # Configure MySQL for Zabbix
    - name: Configure MySQL for Zabbix
      mysql_user:
        name: zabbix
        password: "{{ zabbix_mysql_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: Create Zabbix database
      mysql_db:
        name: zabbix
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Import Zabbix database schema
      mysql_db:
        name: zabbix
        state: import
        #target: /usr/share/doc/zabbix-server-mysql*/create.sql.gz 
        target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
        login_unix_socket: /var/run/mysqld/mysqld.sock

    # Configure Zabbix server
    - name: Configure Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^DBName=', line: 'DBName=zabbix' }
        - { regexp: '^DBUser=', line: 'DBUser=zabbix' }
        - { regexp: '^DBPassword=', line: 'DBPassword={{ zabbix_mysql_password }}' }

    # Start Zabbix server and agent
    - name: Start Zabbix server and agent
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent

    # Configure Apache for Zabbix frontend
    - name: Configure Apache for Zabbix frontend
      lineinfile:
        path: /etc/apache2/conf-enabled/zabbix.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"