    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-pgsql
          - postgresql
          - postgresql-contrib
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - zabbix-agent
          - python3
          - python3-pip
        state: present

    - name: Install pymysql python package
      ansible.builtin.pip:
        name: psycopg2-binary
    
    - name: Create Zabbix database
      postgresql_db:
        state: present
        name: "{{ zabbix_db_name }}"
      become: true
      become_user: postgres
    
    - name: Create Zabbix database user
      postgresql_user:
        db: "{{ zabbix_db_name }}"
        name: "{{ zabbix_db_user }}"
        password: "{{ zabbix_db_pass }}"
        priv: "{{ zabbix_db_name }}.*:ALL"
        state: present
    
    - name: Import Zabbix database schema
      shell: psql -U {{ zabbix_db_user }} -d {{ zabbix_db_name }} -f /usr/share/doc/zabbix-server-pgsql*/create.sql
      become: true
    
    - name: Configure Zabbix server
      copy:
        src: /etc/zabbix/zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf
        owner: root
        group: root
        mode: '0644'

    
    - name: Configure Zabbix frontend
      copy:
        src: /etc/zabbix/apache.conf
        dest: /etc/apache2/conf-available/zabbix.conf
        owner: root
        group: root
        mode: '0644'

    

    - name: Restart Zabbix server
      service:
        name: zabbix-server
        state: restarted
    
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted

