- name: Playbook to replace placeholder passwords with secrets from HashiCorp Vault
  hosts: localhost
  tasks:
  - name: Read the latest version of kv2 secrets from from the domain-creds vault
    community.hashi_vault.vault_read:
      url: https://vault.nasdenissen.synology.me
      path: kv-woningbouw/data/domain-creds
      auth_method: token
      token: 
    register: secret
    delegate_to: "127.0.0.1"

  - name: Replace local admin placeholder password with secret for file_servers.yml
    ansible.builtin.replace:
      path: ./inventory/group_vars/file_servers.yml
      regexp: "winrm_placeholderpass"
      replace: "{{ secret.data.data.data.winrm-password }}"

  - name: Replace local admin placeholder password with secret for file_servers.yml
   ansible.builtin.replace:
     path: ./inventory/group_vars/file_servers.yml
     regexp: "dcsafemode_placeholderpass"
     replace: "{{ secret.data.data.data.dc_safe_mode_password }}"

  - name: Replace local admin placeholder password with secret for file_servers.yml
   ansible.builtin.replace:
     path: ./inventory/group_vars/dc_mainfontys.yml
     regexp: "dcwinadmin_placeholderpass"
     replace: "{{ secret.data.data.data.dc_win_adminpass }}"

  - name: Replace local admin placeholder password with secret for file_servers.yml
   ansible.builtin.replace:
     path: ./inventory/group_vars/domain_controllers.yml
     regexp: "dcsafemode_placeholderpass"
     replace: "{{ secret.data.data.data.dc_safe_mode_password }}"

  - name: Replace local admin placeholder password with secret for file_servers.yml
    ansible.builtin.replace:
      path: ./inventory/group_vars/domain_controllers.yml
      regexp: "winrm_placeholderpass"
      replace: "{{ secret.data.data.data.winrm-password }}"

      